version: '3'
services:
  react-docker:
    networks:
      - capynetwork
    container_name: react-docker
    build:
      context: ./
    ports:
      - "3000:3000"
    # stdin_open: true
    volumes:
       - ./react-docker:/usr/src/app/react-docker
       - /usr/src/app/react-docker/node_modules

networks:
  capynetwork:
    driver: bridge