name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Test server connection
        run: curl -I http://localhost:3000
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: ''
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
