name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Start server and run tests
        run: |
          npm install -g start-server-and-test
          start-server-and-test npm:start http://[::1]:3000 cy:run
        env:
          CYPRESS_BASE_URL: http://[::1]:3000

